"use strict";
(function(root){
const TYPES=Object.freeze({TUTORIAL:"prologue_tutorial",WILDERNESS:"prologue_wilderness",CHAPTER1_FOREST:"chapter1_forest"});
const STORY_MAPS={
[TYPES.TUTORIAL]:{id:TYPES.TUTORIAL,name:"教学地图",kind:"story",spawn:{x:8.5,y:24.5,dir:{x:1,y:0},clearForwardSeconds:3},cleanMap:true,solidOutside:[4,16,51,16],obstacles:[],beans:[[16,24],[24,24],[32,24],[42,24],[48,24],[51,24]],gates:[{id:"tutorial_fragile_gate",kind:"fragile_gate",x:48,y:16,w:3,h:1,need:3,breakEvent:"map.fragile_gate_broken"}],exits:[{id:"tutorial_exit",rect:[47,14,5,3],requiresGate:"tutorial_fragile_gate",targetMap:TYPES.WILDERNESS,targetSpawn:"wilderness_entry"}],interactions:{mechanics:["tutorial_fragile_gate"],exits:["tutorial_exit"]},npcs:[],enemySpawns:[],rules:{allowFreeSnakeAfterTimeout:true,exitRequiresGate:true,beanTarget:0}},
[TYPES.WILDERNESS]:{id:TYPES.WILDERNESS,name:"荒野",kind:"story",spawn:{x:7.5,y:24.5,dir:{x:1,y:0},clearForwardSeconds:3},obstacles:[[4,12,60,1],[4,36,60,1],[4,12,1,11],[4,28,1,8],[63,12,1,25],[20,18,2,2],[31,29,2,2],[48,16,2,2]],beans:[],gates:[],exits:[],interactions:{actors:["keti"]},npcs:[{id:"keti",kind:"keti",x:42.5,y:24.5}],enemySpawns:[],entryPoints:{wilderness_entry:{x:7.5,y:24.5,dir:{x:1,y:0}}},rules:{clearForwardSeconds:3,spawnProtectionSeconds:3,beanTarget:10,initialRandomBeans:8,beanRespawn:3}},
[TYPES.CHAPTER1_FOREST]:{id:TYPES.CHAPTER1_FOREST,name:"森林",kind:"story",chapter:"chapter1",spawn:{x:7.5,y:24.5,dir:{x:1,y:0},clearForwardSeconds:3},cleanMap:true,obstacles:[[18,15,3,2],[28,31,4,2],[42,12,3,3],[53,29,4,2]],beans:[],gates:[],exits:[],interactions:{actors:["ajie","lisi"],items:["forest_sword"]},items:[{storyId:"forest_sword",id:"ironSword",x:31.5,y:19.5,interactive:true}],npcs:[{id:"ajie",kind:"ajie",x:48.5,y:22.5,damageable:false,patrol:[[48.5,22.5],[55.5,22.5]],speed:1},{id:"lisi",kind:"lisi",x:50.5,y:25.5,damageable:false,patrol:[[50.5,25.5],[57.5,25.5]],speed:1}],enemySpawns:[{type:"flower",x:29.5,y:19.5}],rules:{clearForwardSeconds:3,spawnProtectionSeconds:3,beanTarget:12,initialRandomBeans:12,beanRespawn:3}}
};
root.IMS_STORY_MAPS={TYPES,STORY_MAPS,clone:value=>JSON.parse(JSON.stringify(value))};
})(typeof window!=="undefined"?window:globalThis);
